version: '2'

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sacred
    ports:
      - 27017:27017

  sacredboard:
    build:
      context: .
      dockerfile: Dockerfile.sacredboard
    image: sacredboard
    restart: always
    ports:
      - 5000:5000

volumes:
  db-data:
